name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: oracle-1gb

    steps:
      - name: Atualiza o código
        uses: actions/checkout@v4

      - name: Instala as dependências
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Inicia ou reinicia o serviço pm2
        run: |
          pm2 restart esp-bus.api || pm2 start dist/index.js --name esp-bus.api
          pm2 save
