name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: oracle-1gb
    environment: production

    steps:
      - name: Atualiza o código
        uses: actions/checkout@v4

      - name: Cria o .env
        run: |
          touch .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> .env

      - name: Instala as dependências
        run: npm install
      
      - name: Inicia containers
        run: docker compose up -d

      - name: Builda o projeto
        run: npm run build

      - name: Inicia ou reinicia o serviço pm2
        run: |
          pm2 restart esp-bus.api || pm2 start dist/index.js --name esp-bus.api
          pm2 save
